<?php
	$admin_password = "fossil27";

	/*
	 * database related
	 */
	$db_host = "localhost";
	$db_user = "root";
	$db_password = "fossil27";
	$db_name = "dvac";

	/* upload directory */
	$upload_dir = "/case/uploads/";

	/* num_items_per_fetch
	 * specifies the number of items (cases) fetched and displayed
	 * per request for a case list. Remaining items can be displayed
	 * using the 'Show More' button.
	 * 
	 * NOTE: If this number is changed, do not forget to update
	 * caselist.js, which hardcodes this number to decide whether the
	 * 'more' button is displayed.
	 */
	$num_items_per_fetch = 10;

	/* num_days_recent_activity
	 * this specifies the number of days considered for recent activity.
	 */
	$num_days_recent_activity = 30;

	/* num_recent_activities_per_case
	 * this specifies the number of recent activities listed per case
	 * in the 'recent activity' page.
	 */
	$num_recent_activities_per_case = 3;

	/* num_days_upcoming_hearings
	 * this specifies the number of days to be considered to decide an
	 * 'upcoming' hearing. for eg, if this value is 5, a hearing is
	 * considered upcoming if it is in the next 5 days, and not considered
	 * upcoming if it is scheduled beyond 5 days.
	 * WARNING: This is obsolete now. All upcoming hearings are listed now.
	 */
	$num_days_upcoming_hearings = 5;

	/* user grades
	 * each user has a grade, which is a number corresponding
	 * to his current designation. it is intentionally defined
	 * in gaps of 10 to accomodate new grades in the future.
	 */
	$grades = array(
			"Inspector"	=> 10,
			"DSP"		=> 20,
			"ADSP"		=> 30,
			"SP"		=> 40,
			"Deputy Dir"	=> 50,
			"Joint Dir"	=> 60,
			"Director"	=> 70
			);

	/* courts
	 * court locations where DVAC cases/proceedings happen.
	 */
	$courts = array(
			"Madras"	=> 1,
			"Madurai"	=> 2,
			"Supreme Court"	=> 3
			);

	/* counsels
	 * list of counsels who can appear on a dvac case proceeding
	 */
	$counsels = array(
			"Advocate General"		=> 1,
			"Addl. Advocate General"	=> 2,
			"Public Prosecutor"		=> 3,
			"Addl. Public Prosecutor"	=> 4,
			"Government Pleader"		=> 5,
			"Addl. Government Pleader"	=> 6,
			"Spl. Public Prosecutor"	=> 7,
			"Spl. Government Pleader"	=> 8,
			"Government Advocate"		=> 9
			);

	/* locations
	 * locations of dvac offices or dvac officers.
	 */
	$locations = array(
			"Chennai"		=> 1,
			"Madurai"		=> 2,
			"Coimbatore"		=> 3,
			"Tirunelveli"		=> 4
			);

	/* categories
	 * categories to which a court case can belong.
	 */
	$categories = array(
			"Crl.OP"		=> 1,
			"Crl.RC"		=> 2,
			"Crl.Appeal"		=> 3,
			"WP"			=> 4,
			"WA"			=> 5,
			"Contempt Petition"	=> 6,
			"Contempt Appeal"	=> 7,
			"SR.No"			=> 8,
			"Misc"			=> 9,
			"Crl.MP"		=> 10,
			"SLP(Civil)"		=> 11,
			"SLP(Criminal)"		=> 12,
			"Diary No"		=> 13
			);

	/* activities
	 * list of activities for court cases.
	 */
	$activities = array(
			"ADDCASE"		=> 1,
			"UPDATECASE"		=> 2,
			"ADDPROCEEDING"		=> 3,
			"ADDCOMMENT"		=> 4,
			"ASSIGN"		=> 5,
			"CHANGESTATUS"		=> 6,
			"CLOSE"			=> 7,
			"ATTACH"		=> 8,
			"CHANGEDVACSTATUS"	=> 9
			);

	/* statuses
	 * court case statuses.
	 */
	$statuses = array(
		"OPEN"				=> 10,
		"CLOSED"			=> 30
	);

	/* dvac statuses
	 * dvac status of the case.
	 * this is independant of court case status.
	 * ie, court status can be closed, but case can still be open 
	 * with dvac.
	 */
	$dvac_statuses = array(
		"DVAC_OPEN"			=> 10,
		"DVAC_CLOSED"			=> 20
	);
	
	/* disposals.
	 * court case disposals.
	 */
	$disposals = array(
			"NONE"			=> 1,
			"ADJOURNED"		=> 2,
			"INTERIM ORDER PASSED"	=> 3,
			"FINAL ORDER PASSED"	=> 4,
			"OTHER"			=> 5
			);

	/* attachment_types
	 * attachment types
	 */
	$attachment_types = array(
			"UNSPECIFIED"		=> 0,
			"INTERIM ORDER"		=> 1,
			"FINAL ORDER"		=> 2,
			"OTHER"			=> 3
			);


	/* reporting_officer_ids.
	 * the mysql db ids of reporting officers.
	 * these officers need to have special permission to view
	 * and update all cases, without applying any team filter.
	 */
	$reporting_officer_ids = array(10);

	/* sms_enabled
	 * this can be used to enable/disable the sms feature.
	 */
	$sms_enabled = 1;

	/* sms_list
	 * for each activity, list of users to whom sms will be sent.
	 * the possible values for the list (SMS_xxx) are also set below.
	 *
	 * note that this list is only for cases open in court.
	 * for cases open with dvac, if list value is not SMS_NONE,
	 * sms will always be sent to all ancestors.
	 *
	 * the PROCEEDINGLOOKAHEAD is a special activity added for the
	 * sms/proceedings_lookahead.php. this activity is ONLY
	 * generated by the proceeding lookahead checker to send an
	 * advance sms to the officers.
	 */
	$SMS_NONE = 0;
	$SMS_SELF_PARENT = 1;
	$SMS_ANCESTORS = 2;
	$sms_list = array(
			"ADDCASE"		=> $SMS_ANCESTORS,
			"UPDATECASE"		=> $SMS_NONE,
			"ADDPROCEEDING"		=> $SMS_SELF_PARENT,
			"ADDCOMMENT"		=> $SMS_SELF_PARENT,
			"ASSIGN"		=> $SMS_SELF_PARENT,
			"CHANGESTATUS"		=> $SMS_NONE,
			"CHANGEDVACSTATUS"	=> $SMS_NONE,
			"CLOSE"			=> $SMS_NONE,
			"ATTACH"		=> $SMS_NONE,
			"PROCEEDINGLOOKAHEAD"	=> $SMS_SELF_PARENT
			);

	/* num_days_proceeding_lookahead
	 * this value specifies how many days ahead the proceedings lookahead
	 * script should check for proceedings to decide whether to send an
	 * advance sms to the officers.
	 */
	$num_days_proceeding_lookahead = 7;

	/* directions
	 * Possible directions from court.
	 * Specified when case is open with dvac.
	 */
	$directions = array(
			"DIRECTION 1"		=> 10,
			"DIRECTION 2"		=> 20,
			"Otherwise Important"	=> 0
			);

	/* judge_prefix
	 * Prefix to be used to address judges.
	 * Eg, Justice, Hon'ble Justice etc.
	 */
	$judge_prefix = "Hon'ble Justice";
?>
